### ISSUE TITLE
Cambio de idioma y añadir referencias 

### ISSUE THREAD

**Issue by espinr** [UO283428/AsturiasAPie#1]
@UO283428 , gracias por tu ejemplo. 
Como comentamos, estoy procediendo a enlazar tu ejemplo desde las (implementaciones de Heritage in....)[https://github.com/OW2-MiniApp-Initiative/poi-miniapp/blob/main/docs/implementations.json]. Un par de comentarios antes de enlazarlo:

[ ] Cambia el tag del idioma [en] por [es], ya que está en castellano. Si lo prefieres, que estaría bien, podrías añadir los puntos también en inglés, por lo que únicamente tendrías que crear otro objeto como el que tienes en `en`. Puedes ver algún ejemplo que tiene varios idiomas como el de las [mujeres parisinas](https://ow2-quick-app-initiative.github.io/poi-quick-app-implementations/fr/paris/women/data.json).
[ ] Añade atribución a la fuente donde has sacado las imágenes y asegúrate que las puedes usar. Echa un vistazo al ejemplo anterior donde puedes ver cómo se usa. Es un miembro `attributions` dentro de cada uno de los puntos con un array de textos sobre los recursos usados.

Muchas gracias!!!

**Comment by UO283428** [comment]
@espinr, siguiendo tus indicaciones, he agregado los puntos en inglés, siguiendo el modelo de las mujeres parisinas. Todo parece estar en orden.

Asimismo, he sustituido las imágenes anteriores por otras que cuentan con licencia adecuada, y he incluido en la sección de atribuciones los enlaces correspondientes para asegurar su uso legítimo.

Muchas gracias por tu tiempo y orientación!!

**Comment by espinr** [comment]
Genial! Muchas gracias, Carlos.

Aquí lo tienes: https://heritagein.info/asturias/ --> cuando actualices los puntos, seguirá enlazado con esta URL.

**Comment by espinr** [comment]
Por cierto, puedes poner tu nombre (en el acerca de...) y alguna referencia para que sepa quién lo ha hecho. Saludos!
